// Repository contract — trait that application code targets.
// Provider-specific impls are generated at compile-time.

use crate::error::DbResult;

/// Marker trait for semantic repositories.
/// Concrete impls generated by #[vil_repository] macro.
pub trait VilRepository: Send + Sync {
    /// Repository name (for logging/diagnostics).
    fn repo_name(&self) -> &str;
    /// Datasource this repository targets.
    fn datasource(&self) -> &str;
}

/// Standard CRUD operations — generated by derive macro.
/// Each method maps to a single provider call (1 vtable dispatch).
#[async_trait::async_trait]
pub trait CrudRepository<T: Send + Sync>: VilRepository {
    async fn find_by_id(&self, id: i64) -> DbResult<Option<T>>;
    async fn find_all(&self) -> DbResult<Vec<T>>;
    async fn insert(&self, entity: &T) -> DbResult<i64>;
    async fn update(&self, id: i64, entity: &T) -> DbResult<bool>;
    async fn delete(&self, id: i64) -> DbResult<bool>;
    async fn count(&self) -> DbResult<u64>;
    async fn exists(&self, id: i64) -> DbResult<bool>;
}
