//! Tier B AI Semantic Types — lightweight semantic classification for dynamic types.
//!
//! Unlike Tier A (`#[vil_state]`, `#[vil_event]`) which requires fixed-size
//! VASI-compliant types for SHM zero-copy, Tier B works with any Serialize/Deserialize
//! type (String, Vec, HashMap, etc.) and provides:
//!
//! - Semantic classification (event, fault, state, decision)
//! - Lane routing metadata (data, control, trigger)
//! - Auto-observability integration
//! - No SHM/memcpy requirement
//!
//! Tier A: `#[vil_event]` → SHM zero-copy, fixed-size only
//! Tier B: `#[derive(VilAiEvent)]` → JSON-compatible, any type

use serde::{Serialize, Deserialize};

/// Semantic kind for AI types (Tier B).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AiSemanticKind {
    Event,
    Fault,
    State,
    Decision,
}

/// Lane classification for AI types (Tier B).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AiLane {
    /// Immutable data: events, query results, responses
    Data,
    /// Error signals: faults, failures, alerts
    Control,
    /// Routing decisions: agent actions, model selection
    Trigger,
}

/// Trait implemented by all Tier B AI semantic types.
///
/// Generated by derive macros: `VilAiEvent`, `VilAiFault`, `VilAiState`, `VilAiDecision`.
pub trait AiSemantic: Serialize + Send + Sync {
    /// Semantic classification of this type.
    fn semantic_kind() -> AiSemanticKind;
    /// Which Tri-Lane this type logically belongs to.
    fn lane() -> AiLane;
    /// Type name for observability/tracing.
    fn type_name() -> &'static str;
}

/// Metadata envelope for AI semantic types — wraps any AiSemantic value
/// with trace context for observability.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiSemanticEnvelope<T: Serialize> {
    pub kind: AiSemanticKind,
    pub lane: AiLane,
    pub type_name: String,
    pub timestamp_ms: u64,
    pub trace_id: Option<String>,
    pub payload: T,
}

impl<T: AiSemantic + Serialize> AiSemanticEnvelope<T> {
    pub fn wrap(value: T) -> Self {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;
        Self {
            kind: T::semantic_kind(),
            lane: T::lane(),
            type_name: T::type_name().to_string(),
            timestamp_ms: now,
            trace_id: None,
            payload: value,
        }
    }

    pub fn with_trace(mut self, trace_id: impl Into<String>) -> Self {
        self.trace_id = Some(trace_id.into());
        self
    }
}
