// Auto-generated by: vil compile (server mode)
// Source: test-wizard v6.0.0
// Endpoints: 0
// DO NOT EDIT — regenerate from source

#![allow(unused_imports, dead_code)]

use vil_server::prelude::*;
use vil_server::tracing::Instrument;
use serde::{Serialize, Deserialize};

#[tokio::main]
async fn main() {
    let svc = ServiceProcess::new("test-wizard")
    ;

    println!("VIL Server: test-wizard — {} endpoint(s) on port 8080", 0);

    VilApp::new("test-wizard")
        .port(8080)
        .service(svc)
        .run()
        .await;
}
