// ╔════════════════════════════════════════════════════════════╗
// ║  011 — Product Catalog API (GraphQL)                      ║
// ╠════════════════════════════════════════════════════════════╣
// ║  Pattern:  VX_APP                                           ║
// ║  Token:    N/A (HTTP server)                                ║
// ║  Features: ShmSlice, VilResponse                            ║
// ║  Domain:   E-commerce product catalog with nested queries,  ║
// ║            filtering, and real-time inventory subscriptions  ║
// ╚════════════════════════════════════════════════════════════╝
// basic-usage-graphql-api — GraphQL Auto-Generated from Entity Definitions (VX Architecture)
// =============================================================================
//
// BUSINESS CONTEXT:
//   E-commerce product catalog API serving the storefront and admin dashboard.
//   GraphQL enables flexible queries: the storefront fetches minimal product
//   cards (id, name, price), while the admin dashboard queries full details
//   with nested customer + order history. Schema auto-generation from entities
//   keeps the API in sync with the database without manual resolver wiring.
//
// Demonstrates vil_graphql's VilSchemaBuilder to auto-generate a GraphQL
// schema from entity definitions, using the VX Process-Oriented architecture
// (VilApp + ServiceProcess).
//
// VX highlights:
//   - ServiceProcess groups endpoints as a logical Process
//   - VilApp orchestrates processes with Tri-Lane mesh
//   - Handlers stay EXACTLY the same as classic vil-server
//
// Routes:
//   GET  /              → overview page (text)
//   GET  /schema        → describes the GraphQL schema generated from entities
//   GET  /entities      → list registered entities (Order, Customer)
//   POST /query         → in-memory GraphQL query endpoint (JSON → example data)
//
// Built-in endpoints (auto-provided by VilApp):
//   GET  /health        → health check
//   GET  /ready         → readiness probe
//   GET  /metrics       → Prometheus-style metrics
//   GET  /info          → server info
//
// Run:
//   cargo run -p basic-usage-graphql-api
//
// Test:
//   curl http://localhost:8080/api/graphql/
//   curl http://localhost:8080/api/graphql/schema
//   curl http://localhost:8080/api/graphql/entities
//   curl -X POST http://localhost:8080/api/graphql/query \
//     -H 'Content-Type: application/json' \
//     -d '{"query":"{ orders { id total } }"}'
//   curl http://localhost:8080/health
// =============================================================================

use vil_server::prelude::*;
use vil_graphql::{GraphQLConfig, VilSchemaBuilder};
use vil_graphql::schema::{EntityDef, FieldDef};

// ---------------------------------------------------------------------------
// Domain models — typed response structs
// ---------------------------------------------------------------------------

/// Response for GET /api/schema.
#[derive(Clone, Debug, Serialize, Deserialize, VilModel)]
struct SchemaInfoResponse {
    graphql_schema: GraphqlSchemaDetail,
    config: GraphqlConfigDetail,
    note: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, VilModel)]
struct GraphqlSchemaDetail {
    entity_count: usize,
    types: Vec<String>,
    queries: Vec<String>,
    mutations: Vec<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, VilModel)]
struct GraphqlConfigDetail {
    playground_enabled: bool,
    introspection_enabled: bool,
    max_depth: usize,
    max_complexity: usize,
    default_page_size: usize,
    max_page_size: usize,
}

/// Response for GET /api/entities.
#[derive(Clone, Debug, Serialize, Deserialize, VilModel)]
struct EntityListResponse {
    registered_entities: Vec<String>,
    entity_count: usize,
    entities: Vec<EntityDetail>,
}

#[derive(Clone, Debug, Serialize, Deserialize, VilModel)]
struct EntityDetail {
    name: String,
    table: String,
    source: String,
    primary_key: String,
    fields: Vec<String>,
    auto_generated: AutoGenerated,
}

#[derive(Clone, Debug, Serialize, Deserialize, VilModel)]
struct AutoGenerated {
    queries: Vec<String>,
    mutations: Vec<String>,
}

/// Response for POST /api/query (success cases).
#[derive(Clone, Debug, Serialize, Deserialize, VilModel)]
struct QueryResponse {
    data: serde_json::Value,
    extensions: QueryExtensions,
}

#[derive(Clone, Debug, Serialize, Deserialize, VilModel)]
struct QueryExtensions {
    #[serde(skip_serializing_if = "Option::is_none")]
    complexity: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    depth: Option<u32>,
    is_demo: bool,
}

// ---------------------------------------------------------------------------
// GraphQL configuration — mirrors vil-server.yaml graphql section
// ---------------------------------------------------------------------------
// max_depth=10 prevents deeply nested queries that could DoS the catalog.
// max_complexity=1000 bounds the cost of queries joining Order+Customer.

/// Build the GraphQL configuration for this service.
fn graphql_config() -> GraphQLConfig {
    GraphQLConfig {
        enabled: true,
        playground: true,
        max_depth: 10,
        max_complexity: 1000,
        introspection: true,
        default_page_size: 20,
        max_page_size: 100,
    }
}

/// Build the schema builder with registered entities.
/// In production, entities come from #[derive(VilEntity)] macros;
/// here we register them manually to show the API surface.
///
/// Business entities:
///   Order  — purchase transaction (links customer, tracks fulfillment status)
///   Customer — buyer profile with loyalty tier (gold/silver/bronze)
fn build_schema() -> VilSchemaBuilder {
    VilSchemaBuilder::new(graphql_config())
        .entity(EntityDef {
            name: "Order".to_string(),
            table: "orders".to_string(),
            source: "primary".to_string(),
            primary_key: "id".to_string(),
            fields: vec![
                FieldDef { name: "id".into(), graphql_type: "Int!".into() },
                FieldDef { name: "customer_id".into(), graphql_type: "Int!".into() },
                FieldDef { name: "total".into(), graphql_type: "Float!".into() },
                FieldDef { name: "status".into(), graphql_type: "String!".into() },
                FieldDef { name: "created_at".into(), graphql_type: "String!".into() },
            ],
        })
        .entity(EntityDef {
            name: "Customer".to_string(),
            table: "customers".to_string(),
            source: "primary".to_string(),
            primary_key: "id".to_string(),
            fields: vec![
                FieldDef { name: "id".into(), graphql_type: "Int!".into() },
                FieldDef { name: "name".into(), graphql_type: "String!".into() },
                FieldDef { name: "email".into(), graphql_type: "String!".into() },
                FieldDef { name: "tier".into(), graphql_type: "String!".into() },
            ],
        })
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

/// GET / — overview of the GraphQL API example.
async fn index() -> &'static str {
    "VIL GraphQL API Example\n\
     ===========================\n\n\
     This example demonstrates auto-generated GraphQL schemas from entity definitions.\n\n\
     Endpoints:\n\
     - GET  /api/schema    — view the auto-generated GraphQL schema\n\
     - GET  /api/entities  — list registered entities\n\
     - POST /api/query     — in-memory GraphQL query (accepts JSON)\n\n\
     Built-in:\n\
     - GET  /health, /ready, /metrics, /info\n"
}

/// GET /api/schema — describe the auto-generated GraphQL schema.
async fn schema_info() -> VilResponse<SchemaInfoResponse> {
    let builder = build_schema();
    let description = builder.describe_schema();
    let config = builder.config();

    VilResponse::ok(SchemaInfoResponse {
        graphql_schema: GraphqlSchemaDetail {
            entity_count: builder.entity_count(),
            types: description.types,
            queries: description.queries,
            mutations: description.mutations,
        },
        config: GraphqlConfigDetail {
            playground_enabled: config.playground,
            introspection_enabled: config.introspection,
            max_depth: config.max_depth,
            max_complexity: config.max_complexity,
            default_page_size: config.default_page_size,
            max_page_size: config.max_page_size,
        },
        note: "In production, this schema is served at /graphql with full execution support.".to_string(),
    })
}

/// GET /api/entities — list registered entities and their fields.
async fn list_entities() -> VilResponse<EntityListResponse> {
    let builder = build_schema();

    let entities = vec![
        EntityDetail {
            name: "Order".to_string(),
            table: "orders".to_string(),
            source: "primary".to_string(),
            primary_key: "id".to_string(),
            fields: vec![
                "id: Int!".into(), "customer_id: Int!".into(), "total: Float!".into(),
                "status: String!".into(), "created_at: String!".into(),
            ],
            auto_generated: AutoGenerated {
                queries: vec![
                    "order(id: Int!): Order".into(),
                    "orders(limit: Int, offset: Int): [Order!]!".into(),
                    "orderCount: Int!".into(),
                ],
                mutations: vec![
                    "createOrder(input: CreateOrderInput!): Order!".into(),
                    "updateOrder(id: Int!, input: UpdateOrderInput!): Order!".into(),
                    "deleteOrder(id: Int!): Boolean!".into(),
                ],
            },
        },
        EntityDetail {
            name: "Customer".to_string(),
            table: "customers".to_string(),
            source: "primary".to_string(),
            primary_key: "id".to_string(),
            fields: vec![
                "id: Int!".into(), "name: String!".into(),
                "email: String!".into(), "tier: String!".into(),
            ],
            auto_generated: AutoGenerated {
                queries: vec![
                    "customer(id: Int!): Customer".into(),
                    "customers(limit: Int, offset: Int): [Customer!]!".into(),
                    "customerCount: Int!".into(),
                ],
                mutations: vec![
                    "createCustomer(input: CreateCustomerInput!): Customer!".into(),
                    "updateCustomer(id: Int!, input: UpdateCustomerInput!): Customer!".into(),
                    "deleteCustomer(id: Int!): Boolean!".into(),
                ],
            },
        },
    ];

    VilResponse::ok(EntityListResponse {
        registered_entities: builder.entity_names(),
        entity_count: builder.entity_count(),
        entities,
    })
}

/// Request body for the in-memory GraphQL query endpoint.
#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct GraphQLRequest {
    query: String,
    #[serde(default)]
    variables: Option<serde_json::Value>,
}

/// POST /api/query — in-memory GraphQL query endpoint.
/// Parses the query string and returns example data based on detected entity names.
async fn graphql_query(
    body: ShmSlice,
) -> HandlerResult<VilResponse<QueryResponse>> {
    let req: GraphQLRequest = body.json().expect("invalid JSON body");
    let query_lower = req.query.to_lowercase();

    // InMemory responses based on query content.
    // In production, VilSchemaBuilder compiles these into real DB queries.
    // The example data below represents typical catalog query results.
    if query_lower.contains("order") {
        Ok(VilResponse::ok(QueryResponse {
            data: serde_json::json!({
                "orders": [
                    { "id": 1, "customer_id": 101, "total": 249.99, "status": "shipped", "created_at": "2025-01-15T10:30:00Z" },
                    { "id": 2, "customer_id": 102, "total": 89.50, "status": "pending", "created_at": "2025-01-16T14:20:00Z" },
                    { "id": 3, "customer_id": 101, "total": 450.00, "status": "delivered", "created_at": "2025-01-17T09:00:00Z" },
                ]
            }),
            extensions: QueryExtensions { complexity: Some(3), depth: Some(1), is_demo: true },
        }))
    } else if query_lower.contains("customer") {
        Ok(VilResponse::ok(QueryResponse {
            data: serde_json::json!({
                "customers": [
                    { "id": 101, "name": "Alice Johnson", "email": "alice@example.com", "tier": "gold" },
                    { "id": 102, "name": "Bob Smith", "email": "bob@example.com", "tier": "silver" },
                ]
            }),
            extensions: QueryExtensions { complexity: Some(2), depth: Some(1), is_demo: true },
        }))
    } else if query_lower.contains("__schema") || query_lower.contains("introspection") {
        let builder = build_schema();
        let desc = builder.describe_schema();
        Ok(VilResponse::ok(QueryResponse {
            data: serde_json::json!({
                "__schema": {
                    "types": desc.types,
                    "queryType": { "name": "Query", "fields": desc.queries },
                    "mutationType": { "name": "Mutation", "fields": desc.mutations },
                }
            }),
            extensions: QueryExtensions { complexity: None, depth: None, is_demo: true },
        }))
    } else {
        Err(VilError::bad_request(format!(
            "InMemory endpoint: unrecognized query. Try querying 'orders' or 'customers'. Received: {}",
            req.query
        )))
    }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() {
    // VX: Define GraphQL service as a Process.
    // The catalog API is a single process — in production you might split
    // read-heavy catalog queries from write-heavy order mutations.
    let graphql_service = ServiceProcess::new("graphql")
        .endpoint(Method::GET, "/", get(index))
        .endpoint(Method::GET, "/schema", get(schema_info))
        .endpoint(Method::GET, "/entities", get(list_entities))
        .endpoint(Method::POST, "/query", post(graphql_query));

    // VX: Run as Process-Oriented app
    VilApp::new("graphql-api")
        .port(8080)
        .service(graphql_service)
        .run()
        .await;
}
